--- 
title: "test number 2" 
output: html_document 
editor_options: 
  chunk_output_type: console
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
``` 


```{r I hereby name this chunk 1} 

library(readr) 
library(ggplot2)
``` 


# Introduction

- read in data 

```{r message=FALSE}

bg_chem <- read_csv("BGchem2008data.csv") 

```

# Analysis 

- calculate summary statistics 

```{r}

nitrate <- mean(bg_chem$NO3)

nitrite <- mean(bg_chem$NO2)

amm <- mean(bg_chem$NH4)

phos <- mean(bg_chem$P)

ratio <- (nitrate + nitrite + amm)/phos

ratio

```

we calculated this to be `r round(ratio)`

we calculated this to be `r (ratio)`


> this ^ puts calculation for the rounded ratio into markdown. remember to put the r in the ` ` thing

- calculate mean Redfield ratio 

- plot Redfield ratio data is from [here](https://myspace.com)


```{r}

plot(bg_chem$P, bg_chem$NO2 + bg_chem$NO3 + bg_chem$NH4)

ggplot(bg_chem, aes((NO3+NO2+NH4)/P))+
  geom_histogram()+
  theme_bw()

ggplot(bg_chem, aes((NO3+NO2+NH4)/P))+
  geom_density()+
  theme_bw()

ggplot(bg_chem, aes(Si/(NO3+NO2+NH4)))+
  geom_histogram()+
  theme_bw()+
  geom_vline(xintercept=1)

ggplot(bg_chem, aes(Si/(NO3+NO2+NH4)))+
  geom_density()+
  theme_bw()+
  geom_vline(xintercept=1)

```



